### PR TITLE
Normalizers should be defined as generators

### LINKED ISSUE #753: Normalizers should be defined as generators
Currently, the return type of a normalizer function is defined as an iterator, but in reality, it's not an iterator but a generator. Therefore it should be corrected.

**Describe the solution you'd like**
The signature of a normalizer function should be:
```python3
run(normalizer_meta: NormalizerMeta, raw: Union[bytes, str]) -> Generator[OOI]
```

### PR DESCRIPTION
**Pull request by kshitiz305**
### Changes
_Please describe the essence of this PR in a few sentences. Mention any breaking changes or required configuration steps._
the return type of a normalizer function is defined as an iterator

### Issue link
_Please add a link to the issue. If there is no issue for this PR, please add it to the project board directly._
https://github.com/minvws/nl-kat-coordination/issues/753

### Proof
_Please add some proof of your working change here, unless this is not required (e.g. this PR is trivial)._

---

### Code Checklist
- [x] This PR only contains functionality relevant to the issue; tickets have been created for newly discovered issues.
- [x] I have written unit tests for the changes or fixes I made.
- [x] For any non-trivial functionality, I have added integration and/or end-to-end tests.
- [x] I have performed a self-review of my code and refactored it to the best of my abilities.

### Communication
- [x] I have informed others of any required `.env` changes files if required and changed the `.env-dist` accordingly.
- [x] I have made corresponding changes to the documentation, if necessary.

---
## Checklist for code reviewers:
Copy-paste the checklist from [the docs/source/templates folder](/docs/source/templates/pull_request_template_review_code.md).

---
## Checklist for QA:
Copy-paste the checklist from [the docs/source/templates folder](/docs/source/templates/pull_request_template_review_qa.md).

### CODE REVIEW

**Review by ammar92 — COMMENTED** [review]
Thanks for your contribution! There is however a type problem: you have to specify both the send type and return type, even if they're both `None` (so `Generic[OOI, None, None]`). Perhaps a better alternative is `Iterable[OOI]` since the normalizer function also returns a generator/iterable (and not an instance of OOI).

**Comment by kshitiz305** [comment]
@ammar92 as mentioned in the issue #753 that the change is 
`run(normalizer_meta: NormalizerMeta, raw: Union[bytes, str]) -> Generator[OOI]`
but in the above you have mentioned that both can be the case of None as well so what should be the change in that case?

**Comment by kshitiz305** [comment]
> > @ammar92 as mentioned in the issue #753 that the change is
> > `run(normalizer_meta: NormalizerMeta, raw: Union[bytes, str]) -> Generator[OOI]`
> > but in the above you have mentioned that both can be the case of None as well so what should be the change in that case?
> 
> The example in the issue is probably a mistake, a `Generator` hint should always contain the yield, send, and return type. As a simpler and correct alternative, you can use `Iterable[OOI]`, so I suggest using that instead of `Generator[OOI, None, None]`.

So no change is required as that is already implemented in the code

**Comment by kshitiz305** [comment]
> > @ammar92 as mentioned in the issue #753 that the change is
> > `run(normalizer_meta: NormalizerMeta, raw: Union[bytes, str]) -> Generator[OOI]`
> > but in the above you have mentioned that both can be the case of None as well so what should be the change in that case?
> 
> The example in the issue is probably a mistake, a `Generator` hint should always contain the yield, send, and return type. As a simpler and correct alternative, you can use `Iterable[OOI]`, so I suggest using that instead of `Generator[OOI, None, None]`.

ok got it let me try that

**Comment by kshitiz305** [comment]
@ammar92 I have made the changes and tested the code in my local kindly approve the checks in workflow so that they can be tested and merged.

**Comment by kshitiz305** [comment]
@ammar92 as mentioned here in the screenshot I have already registered for the license/ca but still it is showing in the pending stage what shall I do.
image

**Comment by Darwinkel** [comment]
@kshitiz305 it could be that the commits do not have the same e-mail as your GitHub account. 
>If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Review by ammar92 — DISMISSED** [review]
No remarks!

**Comment by Darwinkel** [comment]
## Checklist for QA:
- [x] I have checked out this branch, and successfully ran a fresh `make kat`.
- [x] I confirmed that there are no unintended functional regressions in this branch:
    - [x] I have managed to pass the onboarding flow
    - [x] Objects and Findings are created properly
    - [x] Tasks are created and completed properly
- [x] I confirmed that the PR's advertised `feature` or `hotfix` works as intended.

### What works:
* No apparent regressions

**Review by Darwinkel — DISMISSED** [review]

**Review by dekkers — APPROVED** [review]

**Comment by Darwinkel** [comment]
@kshitiz305 can you sign your commits? It's required before we are allowed to merge. Thanks!

**Comment by kshitiz305** [comment]
I have updated the signed commit

**Review by dekkers — DISMISSED** [review]

**Comment by dekkers** [comment]
> @Darwinkel I have updated the signed commit

You only signed the merge commit, but the other commits are still unsigned, and github requires that all of them are signed (you can check on the commits tab of the PR, the first two don't have "verified" next to it). I think the easiest way to fix it is to do `git rebase -i main` and merge everything in one single commit, sign that commit, and do `git push --force`.

**Comment by kshitiz305** [comment]
I am closing the request due to multiple issues in the git created a new branch and a pull request kindly have a look at that 
#829 
@ammar92 @Darwinkel @dekkers Kindly have a look at that.

**Pull request closed without merging**
